on: [workflow_dispatch]
name: Deploy Demo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.AZURE_RG }}

    - uses: Azure/k8s-deploy@v1.4
      with:
        namespace: 'keda-demo'
        manifests: |
          yaml_files/mysql-deployment.yaml
          yaml_files/redis-deployment.yaml
          yaml_files/make-user.yaml
          yaml_files/dummy-deployment.yaml
          yaml_files/app-deployment.yaml
          yaml_files/api-deployment.yaml
